### ISSUE TITLE
Rerun H. Ian without OBC & send output to Ali 

### ISSUE THREAD

**Issue by janahaddad** [oceanmodeling/WW3#10]
To do:
* rerun H. Ian case without BC and output: 
  * subset of possible wave stats (Hrms, Hm0, Tm0, Tp, others? ) at all nodes
  * full spectra at chosen buoys (maybe within reasonable distance from hurricane track) 
* share those outputs with @aliabdolali

**Comment by janahaddad** [comment]
Update from @yunfangsun : testing using NDBCtoolbox to get buoys in hurricane path 
Other possible tools for this: 
* @saeed-moghimi-noaa 's script
* scripts from John Kelley via @SorooshMani-NOAA

**Comment by saeed-moghimi-noaa** [comment]
@janahaddad  @yunfangsun 
See here:
https://github.com/saeed-moghimi-noaa/prep_obs_ca


```python
# Line 250
#coops_ndbc_obs_collector.py

#################
@retry(stop_max_attempt_number=5, wait_fixed=3000)
def get_ndbc(start, end, bbox , sos_name='waves',datum='MSL', verbose=True):
    """
    function to read NBDC data
    ###################
    sos_name = waves    
    all_col = (['station_id', 'sensor_id', 'latitude (degree)', 'longitude (degree)',
           'date_time', 'sea_surface_wave_significant_height (m)',
           'sea_surface_wave_peak_period (s)', 'sea_surface_wave_mean_period (s)',
           'sea_surface_swell_wave_significant_height (m)',
           'sea_surface_swell_wave_period (s)',
           'sea_surface_wind_wave_significant_height (m)',
           'sea_surface_wind_wave_period (s)', 'sea_water_temperature (c)',
           'sea_surface_wave_to_direction (degree)',
           'sea_surface_swell_wave_to_direction (degree)',
           'sea_surface_wind_wave_to_direction (degree)',
           'number_of_frequencies (count)', 'center_frequencies (Hz)',
           'bandwidths (Hz)', 'spectral_energy (m**2/Hz)',
           'mean_wave_direction (degree)', 'principal_wave_direction (degree)',
           'polar_coordinate_r1 (1)', 'polar_coordinate_r2 (1)',
           'calculation_method', 'sampling_rate (Hz)', 'name'])
    
    sos_name = winds    

    all_col = (['station_id', 'sensor_id', 'latitude (degree)', 'longitude (degree)',
       'date_time', 'depth (m)', 'wind_from_direction (degree)',
       'wind_speed (m/s)', 'wind_speed_of_gust (m/s)',
       'upward_air_velocity (m/s)', 'name'])


```

**Comment by janahaddad** [comment]
### Here's the additional info on `ndbc-api` via Soroosh: 

This email is from John:

Based on the sample API queries on the CO-OPS API web page,  it appears that one can obtain obs (WL, WT, Winds, etc.)  from both their NWLON and PORTS observing networks.
Near-real-time observations from NWS Fixed Buoys and NWS C-MAN Stations and from many ROOA operated buoys and coastal stations are available on the [ndbc.noaa.gov](http://ndbc.noaa.gov/) web site.
I don't know  if NDBC has an API yet, but one can obtain their obs via HTTPS or DODS/OPeNDAP  https://www.ndbc.noaa.gov/docs/ndbc_web_data_guide.pdf
However, I found that someone has written 'ndbc-api' to "parse whitespace-delimited oceanographic and atmospheric data distributed as text files for available time ranges, on a station-by-station basis" (https://pypi.org/project/ndbc-api/). I also found ndbc.py at https://pypi.org/project/NDBC/. I imagine there are many others out there.

Also I opened this ticket for Searvey to add this later:
https://github.com/oceanmodeling/searvey/issues/130

**Comment by aliabdolali** [comment]
why you do not try https://dods.ndbc.noaa.gov/
it has near realtime data via OPENDAP, HTTPServer, NCML, UDDC and ISO.
All of our operational validation is being done from this server. And for Great Lakes Waves, we used the same.

**Comment by janahaddad** [comment]
@aliabdolali, @yunfangsun has a completed H. Ian run outputting at all available buoys in domain, with wave params HS WND DPT DIR FP DP WLV CUR 

are those wave params sufficient for the script you're setting up? 

Re: data transfer and logistics moving forward on this, want to set up a quick tag-up for coordination? Can follow up over email...

**Comment by yunfangsun** [comment]
@aliabdolali 

I have uploaded my WW3 mesh for the Atlantic domain (atlantic.msh), and open boundary id and longitude, and latitude (obc_lon_lat_id) to the Google Drive folder. Could you please set the global wave model and produce the spectra for those boundary nodes?

Thank you very much!

Best

Yunfang

**Comment by yunfangsun** [comment]
Hi @aliabdolali @janahaddad 

I have uploaded 
```
ww3.202209_dpt.nc	
ww3.202209_fp.nc	
ww3.202209_hs.nc	
ww3.202209_spec.nc	
ww3.202209_t01.nc
```
to the Google Drive https://drive.google.com/drive/folders/1CVmyF70egGu7Ke-43bLLMYaEpGFFHl1-

Could you please take a look?

Thank you!

**Comment by saeed-moghimi-noaa** [comment]
Hi @yunfangsun 

Did you also upload the spectrum files?

Thanks,
-Saeed

**Comment by yunfangsun** [comment]
Hi @saeed-moghimi-noaa 

`ww3.202209_spec.nc` is the spectrum file.

Best

**Comment by saeed-moghimi-noaa** [comment]
Ok. Thanks.

**Comment by janahaddad** [comment]
See meeting notes here: https://github.com/oceanmodeling/ufs-coastal/discussions/83

**Comment by janahaddad** [comment]
Closing as complete, next steps in this collaborative effort are noted in https://github.com/oceanmodeling/ufs-weather-model/discussions/83
