### ISSUE TITLE
Enable to build WW3 in standalone mode

### ISSUE THREAD

**Issue by uturuncoglu** [oceanmodeling/WW3#2]
**Is your feature request related to a problem? Please describe.**
The current build interface does not allow to build WW3 in standalone mode (without coupling interface). The UFS Coastal requires also running WW3 in standalone mode using same infrastructure. 

This will solve the issue in the existing `coastal_ike_shinnecock_ww3 ` RT. Currently, it does not get find information from its input files and appears all zero (probably coupling interface assign them to all zero). Once we could able to build WW3 in standalone mode, we need to check this particular RT test again.

**Describe the solution you'd like**
Update WW3 build system and enable building model in standalone mode by adding new build option.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by uturuncoglu** [comment]
@pvelissariou1 Okay. I fix the standalone WW3 test by modifying WW3 cap little bit. At this point I just wonder if `coastal_ike_shinnecock_ww3` and `coastal_ike_shinnecock_atm2ww3`are using same forcing or not. I mean are the data in `ww3.inlet`(used by standalone WW3) same with the data used in CDEPS DATM (`wind_atm_fin_ch_time_vec_STR_fixed.nc`). I am just comparing the WW3 output files and the difference is minimal beteween those two runs. I am assuming the data is same but the difference is coming from interpolation. Let me know what you think?

**Comment by pvelissariou1** [comment]
@uturuncoglu The data are the same. We need to dive into this. I am working on PaHM right now. I'll check on this later.

**Comment by uturuncoglu** [comment]
@pvelissariou1 Okay. good to know. I think the implementation is fine. Here is the changes that I did https://github.com/oceanmodeling/WW3/commit/520900e519cae1df94cd582294b64b55db84d789. I am closing this ticket. We could open a new one if we have any issue.
