### ISSUE TITLE
Set up new config for DATM+WW3 RT

### ISSUE THREAD

**Issue by janahaddad** [oceanmodeling/WW3#4]
For Shinnecock cases, H. Sandy forcing, on Orion/Hercules

Set up configuration with connector
Activate removal of ghost elements on the model component side
pass to CDEPS
run RT

Related issue: https://github.com/ESCOMP/CDEPS/issues/249

@pvelissariou1 please add detail and comment as needed

**Comment by pvelissariou1** [comment]
This is in parallel with issue: https://github.com/oceanmodeling/ufs-coastal/issues/58
Might need to incorporate the UFS-Coastal/WW3 test updates here

**Comment by janahaddad** [comment]
closing with oceanmodeling/ufs-coastal#58. Let's open a new WW3 issue if there is one during this process
