### ISSUE TITLE
share the WW3 version with Aron used in UFS so he can take a look

### ISSUE THREAD

**Issue by janahaddad** [oceanmodeling/WW3#7]
Thank you @aronroland for your willingness to help. Can someone share the WW3 version with Aron used in UFS so he can take a look? Thx.

_Originally posted by @josephzhang8 in https://github.com/oceanmodeling/ufs-coastal/issues/32#issuecomment-1998325472_

**Comment by yunfangsun** [comment]
Hi @aronroland @josephzhang8 @saeed-moghimi-noaa 

The version of WW3 in ufs-coastal is [WW3 @ 520900e](https://github.com/oceanmodeling/WW3/tree/520900e519cae1df94cd582294b64b55db84d789)
https://github.com/oceanmodeling/WW3/tree/520900e519cae1df94cd582294b64b55db84d789
